# Generated by Django 6.0.1 on 2026-09-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(default='SAL', help_text='Shown at the start of every sale invoice number, e.g. SAL-20260927-0001', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_terms',
            field=models.TextField(blank=True, help_text='Terms and conditions printed at the bottom of the invoice.'),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_no'), name='unique_sale_invoice_no_per_company'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_invoice_sequence_per_company_key'),
        ),
    ]
