# Generated by Django 6.0.1 on 2026-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicesequence_company_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mill',
            options={'ordering': ['mill_name']},
        ),
        migrations.AddField(
            model_name='mill',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mill',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mill',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
