# Generated by Django 6.0.1 on 2026-09-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_purchase_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Used to suggest a selling price from the landed cost.', max_digits=5),
        ),
        migrations.CreateModel(
            name='PurchaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport / freight'), ('labour', 'Labour / hamali'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('brokerage', 'Brokerage / commission'), ('packing', 'Packing / bags'), ('other', 'Other')], default='transport', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_to', models.CharField(blank=True, help_text='Truck owner, labour contractor, broker...', max_length=150)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
