# Generated by Django 6.0.1 on 2026-10-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_default_margin_percent_purchaseexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['broker_name']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_type',
            field=models.CharField(choices=[('per_bag', '₹ per bag'), ('per_quintal', '₹ per quintal (100 kg)'), ('percent', '% of sale value (before GST)')], default='per_bag', max_length=20),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.broker'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='advance_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='broker_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='broker_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='broker_commission_type',
            field=models.CharField(blank=True, choices=[('per_bag', '₹ per bag'), ('per_quintal', '₹ per quintal (100 kg)'), ('percent', '% of sale value (before GST)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='driver_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_type',
            field=models.CharField(choices=[('none', 'No GST (bill of supply)'), ('cgst_sgst', 'CGST + SGST (same state)'), ('igst', 'IGST (other state)')], default='cgst_sgst', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_bags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='related_type',
            field=models.CharField(choices=[('sale', 'Received from customer'), ('purchase', 'Paid to mill'), ('broker', 'Commission paid to broker')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sale',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='mill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mill'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.CreateModel(
            name='SaleLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField()),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buy_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mill')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lots', to='core.purchaseitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.sale')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.saleitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
