# Generated by Django 6.0.1 on 2026-10-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_link_sales_to_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='purchase_bills/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='entry_source',
            field=models.CharField(blank=True, default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='irn',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
