# Generated by Django 6.0.1 on 2026-10-02 09:21

from django.db import migrations, models


def keep_old_sales_as_they_were(apps, schema_editor):
    """
    Sales saved before this change treated freight as information only, and
    what the customer owed was the invoice total. Keep them exactly that way.
    """
    Sale = apps.get_model("core", "Sale")
    for sale in Sale.objects.all():
        sale.freight_borne_by = "separate"
        sale.net_receivable = sale.total_amount
        sale.save(update_fields=["freight_borne_by", "net_receivable"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchase_bill_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='broker_paid_by',
            field=models.CharField(choices=[('us', 'We pay the broker'), ('customer', 'Party pays the broker (cut from their payment)')], default='us', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='freight_borne_by',
            field=models.CharField(choices=[('us', "We pay the freight (party's part is cut from their payment)"), ('customer', 'Party pays the freight (our advance is added to their bill)'), ('separate', 'Separate - between party and truck')], default='us', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='net_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='other_deductions_note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='received_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='unload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(keep_old_sales_as_they_were, migrations.RunPython.noop),
    ]
