# Generated by Django 6.0.1 on 2026-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sale_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='default_cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='default_loading_rate_per_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Loading charge per kg, used to fill the loading charge on a sale.', max_digits=8),
        ),
        migrations.AddField(
            model_name='sale',
            name='collect_from',
            field=models.CharField(choices=[('customer', 'Customer pays us'), ('broker', 'Broker pays us (after CD and brokerage)')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='loading_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='commission_type',
            field=models.CharField(choices=[('per_kg', '₹ per kg'), ('per_bag', '₹ per bag'), ('per_quintal', '₹ per quintal (100 kg)'), ('percent', '% of sale value (before GST)')], default='per_kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='broker_commission_type',
            field=models.CharField(blank=True, choices=[('per_kg', '₹ per kg'), ('per_bag', '₹ per bag'), ('per_quintal', '₹ per quintal (100 kg)'), ('percent', '% of sale value (before GST)')], default='', max_length=20),
        ),
    ]
