# Generated by Django 6.0.1 on 2026-10-02 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account security',
                'verbose_name_plural': 'account security',
            },
        ),
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='business name')),
                ('owner_name', models.CharField(max_length=200, verbose_name='owner name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobile')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pending sign-up',
                'verbose_name_plural': 'pending sign-ups',
                'indexes': [models.Index(fields=['email'], name='accounts_pe_email_dc1398_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Sign-up')], default='signup', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='accounts.pendingsignup')),
            ],
            options={
                'verbose_name': 'email code',
                'verbose_name_plural': 'email codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
